### ISSUE TITLE
style=True

### ISSUE THREAD

**Issue by newgithubuser2019** [chris1610/sidetable#11]
This
```
df_sidetable = df.stb.freq(['Region'], value='Award_Amount', style=True)
print(df_sidetable)
```
gives me:
`<pandas.io.formats.style.Styler object at 0x00000227AC76F0A0>`
____________________________________________________________________________________________________________________________________
sidetable 0.5.0
pandas 1.0.5
jinja2 2.11.2

**Comment by chris1610** [comment]
Unfortunately this is the way the pandas style API works. The styled object will display in a notebook if you just type `df_sidetable` but if you try to print, you get the styler object instead. I admit its confusing.

If you are in a notebook environment, this approach should work:
```
from IPython.display import display
display(df_sidetable)
```

It's somewhat similar to if you `print(df_sidetable) ` you get a raw text view, not the formatted table. Fortunately you can use `display(df_sidetable)` to render the HTML version.

**Comment by andresgd7** [comment]
well, im having the same trouble with that parameter too.
this:
`df_penguins.stb.missing(style=True)`

trhows this exception: 
<pandas.io.formats.style.Styler at 0x1231fba8790>

Any idea of how to fix it?
