### ISSUE TITLE
AttributeError: *** must be a numeric column

### ISSUE THREAD

**Issue by newgithubuser2019** [chris1610/sidetable#12]
A dataframe has the following columns: colA, col1, col2, sum. Column "sum" is a sum of "col1" and "col2"

This works fine:
`df_sidetable = df.stb.freq(["colA"], value="col2")`

However, this:
`df_sidetable = df.stb.freq(["colA"], value="col1")`
and this:
`df_sidetable = df.stb.freq(["colA"], value="sum")`
return
`AttributeError: *** must be a numeric column`

col1, col2 and sum consist of numbers. I wonder what might be the problem here
______________________________________________________________________________________
sidetable 0.5.0
pandas 1.0.5

**Comment by chris1610** [comment]
If you run `df_sidetable.info()` does it show all the Dtype's as numeric?

This is the code segment I'm using to determine if a column is numeric, can you try it:

```python
from pandas.api.types import is_numeric_dtype
is_numeric_dtype(df_sidetable['sum'])
```

**Comment by newgithubuser2019** [comment]
Both
`print(is_numeric_dtype(df['col1']))`
and
`print(is_numeric_dtype(df['sum']))`
return
`False`

How come i can sum col1 and col2 without it throwing an error?

**Comment by chris1610** [comment]
Now that is a good question. Do you have null values in the data? I wouldn't expect that to be an issue but maybe.

If you're comfortable sharing the data I can look at it and see what is going on. You can attach it here or if you want to share it privately you could email it to me. Whatever you're comfortable with (if anything).

**Comment by newgithubuser2019** [comment]
I was going to attach the dataframe. However after writing the dataframe to parquet and then reading it:
```
import pyarrow as pa
import pyarrow.parquet as pq
table = pa.Table.from_pandas(df_total, preserve_index=True)
pq.write_table(table, filename20)
table = pq.read_table(filename20)
df_total = table.to_pandas()
```
this
```
print(is_numeric_dtype(df_total['col1']))
print(is_numeric_dtype(df_total['col2']))
print(is_numeric_dtype(df_total['sum']))
```
returns:
```
True
True
True
```

And
```
df_sidetable = df_total.stb.freq(["colA"], value="col1")
df_sidetable = df_total.stb.freq(["colA"], value="sum")
```
no longer raises an error

I am not savvy enough to understand what is happening. If you still would like me to share the dataframe i can do that.

**Comment by chris1610** [comment]
I am happy to look at the original DataFrame. I will also keep this ticket open so we can see if this pops up in other instances.

**Comment by newgithubuser2019** [comment]
Sorry if this is a weird question, but how do i share the original dataframe? Do i just copy-paste it here from windows terminal?

**Comment by chris1610** [comment]
Not a weird question at all. It kind of depends on how big the data set is. I think the easiest way would be to dump it to json and then paste the json here or in a gist.

```
df_sidetable.to_json()
```

I can then read in the json and recreate the DataFrame - hopefully :)

**Comment by newgithubuser2019** [comment]
I apologize for the late reply. 

The same thing happens after i dump the dataframe to json and then read from it - the error no longer occurs.

So I can upload a json file, however isn't it going to be useless since you won't be able to reproduce the problem or do I misunderstand something?

**Comment by chris1610** [comment]
Yes. You're correct. It will be hard to troubleshoot if dumping to json makes the error go away. Is the original raw file and Excel or CSV file? Is there a way you can share a portion of that file?

**Comment by newgithubuser2019** [comment]
Unfortunately I can't share raw files. Anyway it doesn't look like it's a sidetable problem. Thank you for trying to troubleshoot it.

**Comment by chris1610** [comment]
Ok. I'm going to close this out for now. Thanks.
