### ISSUE TITLE
"Percent" is used incorrectly

### ISSUE THREAD

**Issue by nathancarter** [chris1610/sidetable#13]
This is a very cool package, so I apologize for creating a ticket with a rather picky purpose.  But as I'm sure you know, units are crucial in data work, and I'm thinking of this from the point of view of an educator, where I want to teach my students to pay attention to things like this.

Throughout the `sidetable` output, the word "Percent" is used as a column heading for columns that do not contain percentages.  Here's an example from the README in this repo:

class | Count | Percent | Cumulative Count | Cumulative Percent
-- | -- | -- | -- | --
Third | 491 | 0.551066 | 491 | 0.551066
First | 216 | 0.242424 | 707 | 0.79349
Second | 184 | 0.20651 | 891 | 1

Percents are out of 100, such as 55%.  Proportions are out of 1.0, such as 0.55.  The columns should either contain values like 55.1066, 24.2424, 20.651 (in the above example) or should be titled "Proportion" instead.

**Comment by chris1610** [comment]
Thanks for opening the ticket. You raise a good point. I did not think about it in the exact mathematical terms but did have some idea that I was using loose language.

I thought I would use the `style=True` parameter to control the display and show the percentage correctly which works as expected. The default case is not correct though.

I am open to your thoughts but I think the best approach would be to convert my results to show the proper percent number (multiply results by 100) and leave the column as "Percent". The term proportion is probably not as universally understood.

I can then make a small modification to my format string to handle the percent display correctly.

Is that the course you would recommend?

**Comment by chris1610** [comment]
I updated version 0.6 to fix these changes. Upgrade using python -m pip install -U sidetable when you get a chance.

**Comment by nathancarter** [comment]
Yes, this makes perfect sense.  Thanks for the super fast turnaround!
