### ISSUE TITLE
[BUG] sidetable does not release memory...

### ISSUE THREAD

**Issue by LaurentEsingle** [chris1610/sidetable#19]
First of all, thank you for your great work.

When working with Sidetable,  dataframe memory is not released. I have noticed this because I am working with large datasets in my application.

Can you try the code below and tell me if I am doing something wrong?

```
import pandas as pd
import sidetable

# loading a 1.2GB data file.
df0 = pd.read_parquet('US_Accidents_June20.parquet')

# extacting frequency stats
column_name = df0.columns[1]
df2 = df0.stb.freq([column_name])

# deleting dataframes objects
del df2
del df0

# memory ==> 2.3GB

Thank you.
```

**Comment by chris1610** [comment]
That's interesting. I don't think you're doing anything wrong with your code. I will need to look into this some more and see if there is something sidetable should be doing differently to manage memory. I don't have ideas off the top of my head but will look into it.

Thanks.

**Comment by chris1610** [comment]
Thanks again for the fix!
