### ISSUE TITLE
append - future warning

### ISSUE THREAD

**Issue by andrej1919** [chris1610/sidetable#26]
Just a kind warning that append will not work in the future:

`/Users/andrej/Library/Python/3.9/lib/python/site-packages/sidetable/sidetable.py:377: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  return self._obj.append(`

**Comment by chris1610** [comment]
Thanks. I have updated the current github code to remove this warning. Feel free to check it out and see if it works for you. I will try to formally release it soon.

**Comment by andrej1919** [comment]
Thanks, it works fine.

**Comment by chris1610** [comment]
Finally deployed new release that includes the fix. Closing out.
