### ISSUE TITLE
Provide wheels on PyPI?

### ISSUE THREAD

**Issue by domdfcoding** [chris1610/sidetable#6]
Hi, 

Would you be able to provide wheels for sidetable on PyPI?

**Comment by chris1610** [comment]
Thanks for raising the issue. I looked into it and it looks like it should be pretty simple. I will include in my next release.

I'll leave this open until 0.4 goes live.

**Comment by chris1610** [comment]
I just updated to version 0.4 and included wheels.

You can upgrade with pip install -U sidetable and it should work.
