### ISSUE TITLE
Add CategoricalDtype Support

### ISSUE THREAD

**Issue by waltpacz** [chris1610/sidetable#7]
If a categorical variable in a DataFrame has a CategoricalDtype with an order,  then sidetable should recognize this and put the results in that order.  This is somewhat along the lines of sorting the row labels.

**Comment by chris1610** [comment]
That's a good point. Do you think it should default to categorical or the numerical sorting?

I think if I implemented ticket #5 that would support take care of this as well. Thoughts?

**Comment by waltpacz** [comment]
It's hard to say about the default.  If CategoricalDtype is applied, then that's what should be used.  Here is a sample I made up for my purposes.  sidetable should produce it like this.  By the way, sidetable should be allow you to omit the cumulative columns when they don't apply.

As a side note, I'm currently working on a book for Springer on analyzing survey data with Python.  I'd love to include sidetable as a replacement for value_counts.

![freqTable01](https://user-images.githubusercontent.com/40068685/85234001-8c842600-b3d8-11ea-95fc-a28a53e1e215.png)

**Comment by waltpacz** [comment]
I may have closed the issue by accident.  Sorry

**Comment by chris1610** [comment]
Thanks for the detailed example.  I think this is feasible with minimal changes.

One other question on the cumulative columns, do you think we should allow selectively dropping the percent and count? I'm thinking I would add an option like `cum_cols=False` and the Cum Count and Cum Percent would be dropped. Does that seem like what you were thinking?

**Comment by chris1610** [comment]
I just released v0.4. You should be able to pip install -U sidetable 

If you pass the argument sort_cols=True it should sort your data by the categorical values.

I also added an option to remove the cumulative columns. Pass cum_cols=False to have the suppressed.
